
analyzer:
  exclude:
    - '**.g.dart'

linter:
  rules:
    - hash_and_equals
    - prefer_is_not_empty
    - camel_case_types
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - empty_statements
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - unrelated_type_equality_checks
    - valid_regexps
    - always_require_non_null_named_parameters
