/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/LostAndFoundIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LostAndFoundIcon {
  LostAndFoundIcon._();

  static const _kFontFam = 'LostAndFoundIcon';
  static const String? _kFontPkg = null;

  static const IconData lost_and_found_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
